:schedule:
  owid_job:
    cron:  '0 0 * * */1' #every day of the week, #'*/10 * * * *'   # Runs once every 10 mins
    class: OwidJob
  country_owid_job:
    cron:  '0 1 * * */1' #1:30 am every day, #'0 */1 * * *' #every hour
    class: CountryOwidJob
  all_owid_latest_stats_job:
    cron:  '30 1 * * */1'
    class: AllOwidLatestStatsJob
  country_owid_latest_stats_job:
    cron: '45 1 * * */1'
    class: CountryOwidLatestStatsJob
  all_travel_advisories_job:
    cron: '0 2 * * */1'
    class: AllTravelAdvisoriesJob
  country_travel_advisory_job:
    cron: '15 2 * * */1'
    class: CountryTravelAdvisoryJob
  all_reopen_eu_job:
    cron: '30 2 * * */1'
    class: AllReopenEuJob